{% set name = "graphql-core" %}
{% set version = "3.2.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/graphql-core/graphql_core-{{ version }}.tar.gz
  sha256: c08eec22f9e40f0bd61d805907e3b3b1b9a320bc606e23dc145eebca07c8fbab

build:
  skip: True  # [py<37]
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - poetry-core >=1,<2
  run:
    - python
    - typing_extensions >=4.1,<5  # [py<310]

test:
  imports:
    - graphql
  source_files:
    - tests
  requires:
    - pytest >=6.2
    - pytest-benchmark >=3.4,<6
    - pip
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/graphql-python/graphql-core
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python 3.6+ port of the GraphQL.js reference implementation of GraphQL.
  description: |
    GraphQL-core 3 is a Python 3.6+ port of GraphQL.js, 
    the JavaScript reference implementation for GraphQL, 
    a query language for APIs created by Facebook.
  dev_url: https://github.com/graphql-python/graphql-core
  doc_url: https://graphql-core-3.readthedocs.io

extra:
  recipe-maintainers:
    - carlodri
    - bollwyvl
    - KingDarBoja
