{% set name = "graphql-core" %}
{% set version = "3.0.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 31e9e62967cc3cb1afc0d4752e2576633adebbdcb14b4c62b9055413c239a48d

build:
  noarch: python
  number: 0
  script:
    - python -c '__import__("os").unlink("pyproject.toml")'
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - graphql
  source_files:
    - tests
  requires:
    - pytest >=5.3,<5.4
    - pytest-asyncio >=0.10,<1
    - pytest-benchmark >=3.2,<4
    - pytest-cov >=2.8,<3
    - pytest-describe >=0.12,<1
  commands:
    - python -c '__import__("os").unlink("tests/test_docs.py")'
    - pytest --cov graphql

about:
  home: https://github.com/graphql-python/graphql-core-next
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Python 3.6+ port of the GraphQL.js reference implementation of GraphQL.'

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
    - bollwyvl
