{% set name = "graphql-core" %}
{% set version = "3.2.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/graphql-core/graphql-core-{{ version }}.tar.gz
  sha256: 06d2aad0ac723e35b1cb47885d3e5c45e956a53bc1b209a9fc5369007fe46676

build:
  skip: True  # [py<37]
  number: 2
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - poetry-core >=1,<2
  run:
    - python
    - typing_extensions >=4.7.1  # [py<38]

test:
  imports:
    - graphql
  source_files:
    - tests
  requires:
    - pytest >=6.2
    - pytest-benchmark >=5.1, <6  # [py>=39]
    - pytest-benchmark >=4.0, <5  # [py<39]
    - pip
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/graphql-python/graphql-core
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python 3.6+ port of the GraphQL.js reference implementation of GraphQL.
  description: |
    GraphQL-core 3 is a Python 3.6+ port of GraphQL.js, 
    the JavaScript reference implementation for GraphQL, 
    a query language for APIs created by Facebook.
  dev_url: https://github.com/graphql-python/graphql-core
  doc_url: https://graphql-core-3.readthedocs.io

extra:
  recipe-maintainers:
    - carlodri
    - bollwyvl
    - KingDarBoja
