{% set version = "3.2.1" %}

package:
  name: graphql-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/graphql-core/graphql-core-{{ version }}.tar.gz
  sha256: 9d1bf141427b7d54be944587c8349df791ce60ade2e3cccaf9c56368c133c201

build:
  skip: True  # [py<37]
  number: 0
  script:
    - python -c '__import__("os").unlink("pyproject.toml")'
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - typing_extensions >=4

test:
  imports:
    - graphql
  source_files:
    - tests
  requires:
    - pytest >=6.2,<7
    - pytest-asyncio >=0.15,<1
    - pytest-benchmark >=3.4,<4
    - pytest-cov >=2.11,<3
    - pytest-describe >=1,<2
    - pytest-timeout >=1.4,<2
    - pip
  commands:
    - pip check
    - python -c '__import__("os").unlink("tests/test_docs.py")'
    - pytest --cov graphql --cov-report term-missing:skip-covered --no-cov-on-fail

about:
  home: https://github.com/graphql-python/graphql-core
  description: |
    GraphQL-core 3 is a Python 3.6+ port of GraphQL.js, 
    the JavaScript reference implementation for GraphQL, 
    a query language for APIs created by Facebook.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python 3.6+ port of the GraphQL.js reference implementation of GraphQL.
  dev_url: https://graphql-core-3.readthedocs.io/en/latest/
  doc_url: https://github.com/graphql-python/graphql-core/tree/main/docs

extra:
  recipe-maintainers:
    - carlodri
    - bollwyvl
    - KingDarBoja
