{% set version = "3.2.0" %}

package:
  name: graphql-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/graphql-core/graphql-core-{{ version }}.tar.gz
  sha256: 86e2a0be008bfde19ef78388de8a725a1d942a9190ca431c24a60837973803ce

build:
  noarch: python
  number: 0
  script:
    - python -c '__import__("os").unlink("pyproject.toml")'
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - graphql
  source_files:
    - tests
  requires:
    - pytest >=6.2,<7
    - pytest-asyncio >=0.15,<1
    - pytest-benchmark >=3.4,<4
    - pytest-cov >=2.11,<3
    - pytest-describe >=1,<2
    - pytest-timeout >=1.4,<2
    - pip
  commands:
    - pip check
    - python -c '__import__("os").unlink("tests/test_docs.py")'
    - pytest --cov graphql --cov-report term-missing:skip-covered --no-cov-on-fail

about:
  home: https://github.com/graphql-python/graphql-core
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python 3.6+ port of the GraphQL.js reference implementation of GraphQL.
  doc_url: https://graphql-core-3.readthedocs.io

extra:
  recipe-maintainers:
    - carlodri
    - bollwyvl
    - KingDarBoja
