travis:
  secure:
    BINSTAR_TOKEN: wfpPfzSOACuX+K+NyqqL59i7I2E//3faJS20ZGW22/XWYqfAf3ZVf14cIrhx87Sj6jzQw0poZlMxWjz6ktO97dr7m1I8jZL5cDW75zk7gFxtGFRWg3oRp04vOl1cggNxFimDebr7SB+L14Lr9vtx627VEgwKgCKR9zIhm4UCWiOn+UMHww0dVAt/0HPgCkX2+ClF2OxceXymMKxuzExSqwkSQ6rjDloMr48A//VINE5NJMBWtaINTc8o2C0XSENwsCJAg/6tymaFmiM52p0ouukqRHwqlzEry6aLmlUVU4myNagjFzYjQZxG34iIiKb/bEx+7X955Gi7hqvLHkVtbVdvt/BwHBqyYPhgcXxFqFk28ZZ/b2yxu7Yd9f0lROjO4znvZPw3X1qBfoibaXB0SLn3Vv2+Udie3fAEyk5lPNtrANDdR3PNW1Y00paFrKt+m5d4gxHCvtQZay+eYUkCMCsC2HXIjh9IDXgSAcIH3JFvve4JJsSD76V+9vKbo825m74sSG54wFJ/yCmdhqhUU4nO2tNcdY33Eny2H7ts7sICptvUrKkPWUp9LE9TAJOI2zfeyAz5ZxAQeOUpAR0ll5d/UMShJeFgG1b3UznJceUutH68bwsXawyYK4bjSyhYnWUfdsV8xcpkS5A+FKmH4cqwWY7D/9ad62UA12415Zo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
